**Mastering NumPy: The Foundation of Data Science in Python**

Welcome to this interactive class! Today we are looking at NumPy (Numerical Python). In this notebook, we will cover:

1. Introduction to NumPy
2. NumPy Arrays vs Python Lists
3. Creation of 1D, 2D, and 3D arrays
4. Special NumPy Functions (zeros, ones, full, etc.)
5. Hands-on Operations with N-dimensional arrays

1. Introduction to Numpy

NumPy is the fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level 
mathematical functions to operate on these arrays efficiently.

In [2]:
!pip install numpy

In [3]:
# Let's start by importing the library
# 'np' is the universal standard alias for NumPy

import numpy as np

print('Numpy imported succesfully!')
print('version:',np.__version__)

Numpy imported succesfully!
version: 2.5.1


**2. NumPy Array vs Python List**

Why do we need NumPy when Python already has built-in lists?

Size: NumPy arrays take up significantly less memory in your machine.
Performance: They are massively faster. NumPy is largely written in C and optimizes memory allocation.
Functionality: NumPy arrays have built-in, highly optimized functions for complex mathematical operations.
Let's run a quick performance test to see the speed difference when adding two lists versus two arrays.

In [4]:
import time 
import numpy as np

size= 1000000

#---PYTHON LIST TEST---
list1=list(range (size))
list2=list(range (size))

start_time=time.time()
result=[(a+b) for a,b in zip(list1,list2)]
print('python list time',(time.time()-start_time)*1000,'milliseconds')

python list time 224.63750839233398 milliseconds


In [5]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# ---NUMPY ARRAY TEST---
arr1=np.arange(size)
arr2=np.arange(size)

start_time=time.time()
result_array =arr1+arr2  #Notice how much cleaner the syntax is!
print('Numpy Arrray Time:',(time.time() -start_time)*1000,'milliseconds')


Numpy Arrray Time: 10.927200317382812 milliseconds


**3. Creation of 1D, 2D and 3D array**

The core of NumPy is the ndarray (N-dimensional array). An array's dimensionality is known as its rank.

1D Array: A list of values (Vector)
2D Array: A list of lists (Matrix / Table with rows and columns)
3D Array: A list of lists of lists (Cube / Tensor)

In [9]:
# 1. Creating a 1d Array
array_1d =np.array([10,20,30,40,50])
print('---1d Array---')
print(array_1d)
print('Dimensions:',array_1d.ndim)
print('Shape:',array_1d.shape) # output is (5,) meaning 5 items in 1 dimension

---1d Array---
[10 20 30 40 50]
Dimensions: 1
Shape: (5,)


In [11]:
# 2. Creating a 2D Array (Pass a list of lists)
array_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])

print('---2d Array---')
print(array_2d)
print('Dimensions:',array_2d.ndim)
print('Shape:',array_2d.shape) # output is (3,3) meaning 3 rows and 3 columns

---2d Array---
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Dimensions: 2
Shape: (3, 3)


In [12]:
# 3. Creating a 3D Array (Pass a list of lists of lists)
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print('---3d Array---')
print(array_3d)
print('Dimensions:',array_3d.ndim)
print('Shape:',array_3d.shape) # output is (2, 2,

---3d Array---
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


**4 & 5. Special NumPy Functions**

Often, we don't type out arrays by hand. We need to generate arrays of a specific shape to hold data later. NumPy provides powerful built-in functions for this:

np.zeros(): Fills array with 0s.
np.ones(): Fills array with 1s.
np.full(): Fills array with a specific number.
np.arange(): Creates sequences of numbers.

In [13]:
# np.zeros() - Great for initializing placeholders
zeros_matrix = np.zeros((3, 4)) # 3 rows, 4 columns
print('---Zeros Matrix---')
print(zeros_matrix)

---Zeros Matrix---
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
# np.ones() 
ones_matrix = np.ones((2, 2))
print('---Ones Matrix---')
print(ones_matrix)

---Ones Matrix---
[[1. 1.]
 [1. 1.]]


In [15]:
# np.full() - Specify shape and the value you want to fill it with
full_matrix = np.full((3, 3), 99) 
print('---Full Matrix---')
print(full_matrix)

---Full Matrix---
[[99 99 99]
 [99 99 99]
 [99 99 99]]


In [16]:
# np.arange() - Start, Stop (exclusive), Step
sequence_array = np.arange(0, 20, 2)
print('---Sequence Array---')
print(sequence_array)

---Sequence Array---
[ 0  2  4  6  8 10 12 14 16 18]


**Hands On: N-dimensional Arrays and Operations**
Let's put it all together. Operations in NumPy are vectorized, meaning they apply to the entire array at once without needing a for loop.

In [20]:
# Setup a 2D Array representing test scores for 3 students across 4 subjects
scores = np.array([[85, 90, 88, 92],
                   [78, 80, 85, 88],
                   [92, 95, 98, 100]])

print('Original Scores Array:')
print(scores)
print('-'*40)

Original Scores Array:
[[ 85  90  88  92]
 [ 78  80  85  88]
 [ 92  95  98 100]]
----------------------------------------


In [21]:
# 1. Scalar Operations (Curve everyone's grade by +5 points)
curved_scores = scores + 5
print('Curved Scores Array:')
print(curved_scores)


Curved Scores Array:
[[ 90  95  93  97]
 [ 83  85  90  93]
 [ 97 100 103 105]]


In [23]:
# 2. Slicing (Extract just Student 1's scores)
# Syntax: array[row_start:row_end, col_start:col_end]
student_1 = scores[0, :]
print('Student 1 Scores:', student_1)

Student 1 Scores: [85 90 88 92]


In [24]:
# Extract just Subject 3's scores for all students
subject_3 = scores[:, 2]
print('Subject 3 Scores:', subject_3)
print('-'*40)

Subject 3 Scores: [88 85 98]
----------------------------------------


In [25]:
# 3. Statistical Operations
print('Maximum score in the class:', np.max(scores))
print('Minimum score in the class:', np.min(scores))
print('Average score in the class:', np.mean(scores))

Maximum score in the class: 100
Minimum score in the class: 78
Average score in the class: 89.25
